### PR TITLE
add delay(ms)

### PR DESCRIPTION
**Pull request by SmartArduino**
line 41: Wire.endTransmission(false) -> Wire.endTransmission()
line45: delay(20);

Modifed above works for me.
My hardware is shtc1 and esp8266.
esp8266 ide of arduino is here:https://github.com/esp8266/Arduino

### CODE REVIEW

**Comment by winkj** [comment]
can you explain the problem you had, and how this is fixing it?

**Comment by SmartArduino** [comment]
Hi, winkj,
I used esp8266 to read temprature and humidty from shtc1. If 'delay(20)' is not added, no data will be read sucessfully. 
I guess this is due to the esp8266 sdk.

**Comment by manibenwa** [comment]
Hai ,

 I have interfaced shtc1 sensor with nodemcu board  (4 and 5 )pins and i uploaded the code  .i got the error  in readsample  .Is there any modifications in do ineed to do in librarys????

**Comment by manibenwa** [comment]
Worked for me after delay(20); is added form above given stuff.Thanks

**Comment by winkj** [comment]
Hi manibenwa, 

Could you try the updated library from https://github.com/Sensirion/arduino-sht? There have been some changes to the I2C handling, so I'm not sure if the delay is still necessary. If it is, I'd like to add it there, too.

winkj/arduino-sht is not maintainted anymore, sensirion/arduino-sht is the official library for the SHT series.

**Pull request closed without merging**
